plugins:
  ai_for_instruments_webhook_url:
    default: ""
    type: string
    client: false

  ai_for_instruments_hmac_secret:
    default: ""
    type: string
    client: false

  ai_for_instruments_categories:
    default: 0
    type: category_list
    client: true
