plugins:
  ai_for_instruments_enabled:
    default: true
    type: boolean
    client: true

  ai_for_instruments_webhook_url:
    default: ""
    type: string
    client: false

  ai_for_instruments_hmac_secret:
    default: ""
    type: string
    client: false

  ai_for_instruments_category:
    default: 0
    type: category
    client: true
